/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as EntrarRouteImport } from "./routes/entrar"
import { Route as AuthRouteImport } from "./routes/_auth"
import { Route as AuthIndexRouteImport } from "./routes/_auth.index"

const EntrarRoute = EntrarRouteImport.update({
  id: "/entrar",
  path: "/entrar",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof AuthIndexRoute
  "/entrar": typeof EntrarRoute
}
export interface FileRoutesByTo {
  "/entrar": typeof EntrarRoute
  "/": typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_auth": typeof AuthRouteWithChildren
  "/entrar": typeof EntrarRoute
  "/_auth/": typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/entrar"
  fileRoutesByTo: FileRoutesByTo
  to: "/entrar" | "/"
  id: "__root__" | "/_auth" | "/entrar" | "/_auth/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  EntrarRoute: typeof EntrarRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/entrar": {
      id: "/entrar"
      path: "/entrar"
      fullPath: "/entrar"
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth/": {
      id: "/_auth/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  EntrarRoute: EntrarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
